name: Bug Report form
description: Bug Report form
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        > Please fill out this bug report form and click `Submit new issue` button at the bottom.
        
        > Remember to add a proper title related with this bug.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe de bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-logs
    attributes:
      label: Logs  (optional)
      description: Log section render as shell codeblock
      render: shell
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Steps to reproduce the behaviour.
      placeholder: |
        1.  Go to '...'
        2.  Click on '....'
        3.  Scroll down to '....'
        4.  See error
    validations:
      required: true
  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: bug-current
    attributes:
      label: Current behaviour
      description: A clear and concise description of what the current behaviour.
    validations:
      required: true
  - type: textarea
    id: bug-additional
    attributes:
      label: Additional Context (optional)
      description: Add any other context about the problem here.
  - type: textarea
    id: bug-workaround
    attributes:
      label: Workaround (optional)
      description: If you have a workaround, please put the details here.
  - type: textarea
    id: bug-code-analysis
    attributes:
      label: Code analysis (optional)
      description: If you already investigated the code, please share your finding here.
