blank_issues_enabled: false
contact_links:
  - name: Secure Banking Access Toolkit community support
    url: https://backstage.forgerock.com/
    about: Please ask and answer questions here.
  - name: Forgerock Secure Banking Toolkit documentation
    url: https://backstage.forgerock.com/
    about: Please read the documentation here.
  - name: Forgerock Secure Banking Access Toolkit security
    url: https://backstage.forgerock.com/
    about: Please report security vulnerabilities here.
