name: Feature Request form
description: Feature Request form
title: "[Feature]: "
labels: ["feature", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > Please fill out this bug report form and click `Submit new issue` button at the bottom.
        
        > Remember to add a proper title related with this feature requested.
  - type: textarea
    id: f-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: |
         I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: f-solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: f-alternative
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: f-additional
    attributes:
      label: Additional context (optional)
      description: Add any other context or screenshots about the feature request here.
