name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/users/jorgesanchezperez/projects/1'
          column_name: 'To do'
